Ch integrate heroku
andela/wger_vulcan pull request #11
Opened 2017-04-03 14:39 UTC by Mbarak-Mbigo

**What does this PR do?**
It integrates heroku deployment

**Description of Task to be completed?**
Integrate local repo to heroku (deployment)

**How should this be manually tested?**
visit `https://wgervulcan.herokuapp.com``

**Any background context you want to provide?**
None

**What are the relevant pivotal tracker stories?**
#142465231

2017-04-03 16:35 UTC, amwaleh requested changes
Great work!! just make sure your development settings are not hard coded, try using a `.env` file.

2017-04-03 16:35 UTC, andela-amwaleh commented on wger/settings.py
> +        'NAME': '/Users/mbarakmbigo/wger_vulcan/database.sqlite',
this has your development/personal settings in it. Let the name of the database be retrieved from  .env

2017-04-03 16:35 UTC, andela-amwaleh commented on wger/settings.py
> +SITE_URL = 'http://localhost:8000'
this might also need to change once on heroku. But am not sure !! please prove me wrong.

2017-04-03 16:35 UTC, andela-amwaleh commented on wger/settings.py
> +MEDIA_ROOT = '/Users/mbarakmbigo/.local/share/wger/media'
Yet again your dev setting have been hard coded

2017-04-03 16:40 UTC, Mbarak-Mbigo commented on wger/settings.py
> +MEDIA_ROOT = '/Users/mbarakmbigo/.local/share/wger/media'
These settings were generated during installation as I followed the app's readme from the github repo. I will change accordingly.

2017-04-03 16:48 UTC, andela-amwaleh commented on wger/settings.py
> +MEDIA_ROOT = '/Users/mbarakmbigo/.local/share/wger/media'
Then believe this files need to be git ignored

2017-04-06 16:45 UTC, amwaleh approved these changes

2017-04-06 16:45 UTC, merged