Ch slack travis integration #142465231
andela/wger_vulcan pull request #2
Opened 2017-03-28 12:32 UTC by andela-layodi

#### What does this PR do? 
Ensures that Travis CI is integrated to Slack.

#### Description of Task to be completed? 
Send slack notifications every time Travis runs after a commit or pull request is made.

#### How should this be manually tested? 
Slack notifications sent to #andela_vulcan_updates channel

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
#142465231

2017-03-29 05:23 UTC, Mbarak-Mbigo reviewed
It looks properly implemented

2017-03-30 19:23 UTC, amwaleh requested changes
Looks good!! just remove the wger-venv

2017-03-30 19:23 UTC, andela-amwaleh commented on .gitignore
> +wger-venv/*
Add this to your global .gitignore

2017-03-30 19:23 UTC, andela-amwaleh commented on .gitignore
> +wger-venv/*
http://islegend.com/development/setting-global-gitignore-mac-windows/

2017-04-03 08:20 UTC, amwaleh approved these changes

2017-04-03 08:21 UTC, merged